apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-app
  name: green-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
      color: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
        color: green
    spec:
      containers:
      - image: paulogorgias/color-app:latest
        name: color-app
        env:
          - name: COLOR
            value: green
        resources: {}
status: {}
