apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probe-pod
  name: probe-pod
spec:
  containers:
  - image: paulogorgias/probe-app
    name: probe-pod
    ports:
      - containerPort: 8000
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
