apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: canary-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: canary-app
status:
  loadBalancer: {}
